// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomesController from "./homes_controller"
application.register("homes", HomesController)

import SearchsController from "./searchs_controller"
application.register("searchs", SearchsController)

import SpotsController from "./spots_controller"
application.register("spots", SpotsController)
